theme: jekyll-theme-minimal
logo: https://github.com/RuxinZhang/FA22_BIMM143/blob/main/Miscellaneous/Pictures/uc_on_strike.JPG?raw=true
title: Runqi Zhang's Bioinformatics Class (BIMM 143, Fall 2022)
email: ruz021@ucsd.edu
